### PR TITLE
Handle redirects when using bearer tokens

### LINKED ISSUE #925: Bearer token authentication fails on redirect
This occurs because we are setting the `Authorization` header manually and `NSURLSession` strips it when following a redirect as a security precaution.

### PR DESCRIPTION
**Pull request by winniequinn**
Closes #925

### CODE REVIEW

File: Simplified/NYPLMyBooksDownloadCenter.m [hunk 1]
```diff
@@ -307,18 +320,74 @@ - (void)URLSession:(__attribute__((unused)) NSURLSession *)session
...
 
+// This is implemented in order to be able to handle redirects when using
+// bearer token authentication.
+- (void)URLSession:(__unused NSURLSession *)session
+              task:(NSURLSessionTask *const)task
+willPerformHTTPRedirection:(__unused NSHTTPURLResponse *)response
+        newRequest:(NSURLRequest *const)request
+ completionHandler:(void (^ const)(NSURLRequest *_Nullable))completionHandler
+{
+  NSUInteger const maxRedirectAttempts = 10;
```
Comment (djds23) [inline Simplified/NYPLMyBooksDownloadCenter.m]: Just curious where this number came from
