### PR TITLE
Bug annotations #672

### LINKED ISSUE #672: Bugsnag: crash at Annotations Header 'get'
[Bugsnag Link](https://app.bugsnag.com/nypl-1/android-open-ebooks/errors/58f3ce137e08960018feabab?filters%5Berror.status%5D%5B%5D=open&filters%5Bevent.since%5D%5B%5D=30d)

Implicitly unwrapped optionals are causing a crash here. Will add optional binding for safety when accessing. Networking methods should handle header errors further down the stream.

### PR DESCRIPTION
**Pull request by gioneill**
Fixes #672  crash when accessing headers var getter.
Should resolve bugsnag bug referenced ticket.

Whatever cause of missing credential header, passing an empty field as the fail-case should allow server and networking method to handle error more gracefully.

### CODE REVIEW

File: Simplified/NYPLAnnotations.swift [hunk 1]
```diff
@@ -142,7 +142,7 @@ final class NYPLAnnotations: NSObject {
           debugPrint(#file, "Posted Last-Read \(((parameters["target"] as! [String:Any])["selector"] as! [String:Any])["value"] as! String)")
         }
       } else {
-        guard let error = error as? NSError else { return }
+        guard let error = error as NSError? else { return }
```
Comment (winniequinn) [inline Simplified/NYPLAnnotations.swift]: This is not directly related to your change per se, but the sum of this code does not seem right to me:

1. The type of response is always `HTTPURLResponse` and can be safely cast using `as!`.

2. If the type of the response is `HTTPURLResponse` and the status code is not 200, we silently ignore it. Not at least logging an error here seems wrong to me, but I think we're actually supposed to be retrying later.

3. The logging code when the response is 200 will crash the app if undocumented keys are not present.

4. The call to `addToOfflineQueue` on line 147 will never be hit because response is always of type `HTTPURLResponse`.

Comment (gioneill) [inline Simplified/NYPLAnnotations.swift]: I'm delaying this to next sprint when Annotations will be fully updated to support bookmarks. The crash fix is left in as a commit, removing implicitly unwrapped optionals.
