### PR TITLE
Offline queue sql fix #897

### LINKED ISSUE #897: SIGTRAP in SQLite.Statement.next() -> [SQLite.Binding?]?
## Error in iOS - Simplified

**SIGTRAP** in **SQLite.Statement.next() -> [SQLite.Binding?]?**

[View on Bugsnag](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a4f7a8156edd600189e25c4?event_id=5a65f14b70eab9001a4bc44f&i=gh&m=ci)

## Stacktrace

    Frameworks/SQLite.framework/SQLite:0 - SQLite.Statement.next() -> [SQLite.Binding?]?
    Frameworks/SQLite.framework/SQLite:0 - partial apply forwarder for closure #1 () -> SQLite.Row? in closure #2 () -> Swift.AnyIterator<SQLite.Row> in SQLite.Connection.prepare(SQLite.QueryType) throws -> Swift.AnySequence<SQLite.Row>
    Frameworks/SQLite.framework/SQLite:0 - partial apply forwarder for reabstraction thunk helper from @callee_owned () -> (@owned SQLite.Row?) to @callee_owned () -> (@out SQLite.Row?)
    Simplified/NYPLNetworkQueue.swift:0 - next
    Simplified/NYPLNetworkQueue.swift:0 - retryQueue
    Simplified/NYPLReachability.m:61 - -[NYPLReachability reachabilityChanged:]
    Simplified/NYPLReachabilityManager.m:96 - ReachabilityCallback

[View full stacktrace](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a4f7a8156edd600189e25c4?event_id=5a65f14b70eab9001a4bc44f&i=gh&m=ci)

*Created by Gregory O'Neill via Bugsnag*

### PR DESCRIPTION
**Pull request by gioneill**
Improves reliability and organization of NetworkQueue in a couple ways:

- Synchronizes an iterator on the sqlite table so that network requests and their completion blocks do not happen on different threads, which is likely to resolve #897 
- Turn NetworkQueue into a singleton instead of fully static class. NYPLReachability doesn't need to "know" about the queue. The instance is created on app launch in the app delegate.

### CODE REVIEW

File: Simplified/NYPLNetworkQueue.swift [hunk 1]
```diff
@@ -1,41 +1,57 @@
...
+ will retry any queued requests and purge them if necessary.
+ */
 final class NetworkQueue: NSObject {
-  
+
+  static let shared = NetworkQueue()
+
+  override init() {
+    super.init()
+    NotificationCenter.default.addObserver(forName: NSNotification.Name.NYPLReachabilityHostIsReachable,
```
Comment (winniequinn) [inline Simplified/NYPLNetworkQueue.swift]: Even though this only gets used via a shared instance for now, you should probably still pair this with a `removeObserver` call in `deinit`.

File: Simplified/NYPLNetworkQueue.swift [hunk 2]
```diff
@@ -1,41 +1,57 @@
...
+                            NSURLErrorCannotConnectToHost,
+                            NSURLErrorNetworkConnectionLost,
+                            NSURLErrorNotConnectedToInternet,
+                            NSURLErrorInternationalRoamingOff,
+                            NSURLErrorCallIsActive,
+                            NSURLErrorDataNotAllowed,
+                            NSURLErrorSecureConnectionFailed]
+  let MaxRetriesInQueue = 5
+
+  let serialQueue = DispatchQueue(label: "org.nypl.labs.SimplyE.networkQueue")
```
Comment (winniequinn) [inline Simplified/NYPLNetworkQueue.swift]: This is too picky perhaps, but I'd recommend the following instead:

```swift
let serialQueue = DispatchQueue(Bundle.main.bundleIdentifier!
                                + "."
                                + String(describing: NetworkQueue.self))
```

This code will continue to work correctly even if the bundle ID changes and it will allow refactoring tools to handle changes to the class name.

File: Simplified/NYPLNetworkQueue.swift [hunk 3]
```diff
@@ -92,31 +108,29 @@ final class NetworkQueue: NSObject {
       Log.error(#file, "SQLite Error: Could not insert or update row")
     }
   }
-  
-  class func retryQueue()
+
+  private func retryQueue()
```
Comment (winniequinn) [inline Simplified/NYPLNetworkQueue.swift]: ❤️

File: Simplified/NYPLNetworkQueue.swift [hunk 4]
```diff
@@ -92,31 +108,29 @@ final class NetworkQueue: NSObject {
...
   {
-    guard let db = startDatabaseConnection() else { return }
-    
-    do {
-      for row in try db.prepare(sqlTable) {
-        self.retry(db: db, requestRow: row)
+    serialQueue.async {
```
Comment (winniequinn) [inline Simplified/NYPLNetworkQueue.swift]: _Extremely_ minor, but you use `serialQueue.async` here and `self.serialQueue.async` below. I'd prefer the latter in both places but consistency would be nice either way.

File: Simplified/NYPLReachability.m [hunk 5]
```diff
@@ -58,7 +60,7 @@ - (void) reachabilityChanged:(NSNotification *)note
     switch (netStatus) {
       case ReachableViaWiFi:
       case ReachableViaWWAN:
-        [NetworkQueue retryQueue];
+        [[NSNotificationCenter defaultCenter] postNotificationName:NYPLReachabilityHostIsReachableNotification object:self];
```
Comment (winniequinn) [inline Simplified/NYPLReachability.m]: Very happy with this change!

**Comment by gioneill** [comment]
Thanks 👍
