### PR TITLE
3D Touch - Nil Casting Crash Fix

### LINKED ISSUE #871: NSInvalidArgumentException in NYPLCatalogGroupedFeedViewController
## Error in iOS - Simplified

**NSInvalidArgumentException** in **NYPLCatalogGroupedFeedViewController**
-[UITableViewCell laneIndex]: unrecognized selector sent to instance 0x126838e00

[View on Bugsnag](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a16eecabfb4af0018909ef9?event_id=5a458d5c0bd30900184a63f5&i=gh&m=ci)

## Stacktrace

    Simplified/NYPLCatalogGroupedFeedViewController.m:308 - -[NYPLCatalogGroupedFeedViewController previewingContext:viewControllerForLocation:]

[View full stacktrace](https://app.bugsnag.com/nypl-1/ios-simplified/errors/5a16eecabfb4af0018909ef9?event_id=5a458d5c0bd30900184a63f5&i=gh&m=ci)

*Created by Gregory O'Neill via Bugsnag*

### PR DESCRIPTION
**Pull request by gioneill**
Protect against nil when trying to cast a collection view cell.

Missed this when updating the GroupedFeedViewController for the same issue before.

Fixes #871

### CODE REVIEW

File: Simplified/NYPLCatalogUngroupedFeedViewController.m [hunk 1]
```diff
@@ -285,11 +285,14 @@ - (UIViewController *)previewingContext:(id<UIViewControllerPreviewing>)previewi
 {
   CGPoint referencePoint = [self.collectionView convertPoint:location fromView:self.view];
   NSIndexPath *indexPath = [self.collectionView indexPathForItemAtPoint:referencePoint];
-  NYPLBookNormalCell *cell = (NYPLBookNormalCell *)[self.collectionView cellForItemAtIndexPath:indexPath];
-  
+  UICollectionViewCell *cell = [self.collectionView cellForItemAtIndexPath:indexPath];
+  if (!cell || ![cell isKindOfClass:[NYPLBookNormalCell class]]) {
```
Comment (winniequinn) [inline Simplified/NYPLCatalogUngroupedFeedViewController.m]: This is a minor thing, but you just need `![cell isKindOfClass:[NYPLBookNormalCell class]]` here: The `!cell` check is redundant.
